"""Make CFP fields nullable

Revision ID: a1bcb7ebcc51
Revises: f117e7265833
Create Date: 2025-04-24 12:34:14.897062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1bcb7ebcc51'
down_revision: Union[str, None] = 'f117e7265833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfps', 'submission_deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cfps', 'conference_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cfps', 'conference_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cfps', 'submission_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfps', 'submission_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('cfps', 'conference_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cfps', 'conference_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cfps', 'submission_deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
