"""Add description field to CFP model

Revision ID: f117e7265833
Revises: 108e1def71f4
Create Date: 2025-04-24 12:29:18.983874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f117e7265833'
down_revision: Union[str, None] = '108e1def71f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfps', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfps', 'description')
    # ### end Alembic commands ###
